---
- hosts: all
  
  tasks:
  
  - name: Run API
    docker_image:
         name: yoav92/docker-app:latest
         build:
          path: ./simple_api
          args:
            log_volume: ./simple_api:/usr/src/app
            listen_port: 5001
         source: build
         
   
  - name: Run apache container
    docker_container:
       name: 'website'
       image: 'php:apache'
       published_ports:
         - "5000:80"
       volumes:
         - "./website:/var/www/html"
       env:
         USERNAME: "toto"
         PASSWORD: "python"

        
   
   
