---
- hosts: all
  
  tasks:
  
   - name: Run API
     docker_container:
        name: 'app-service'
     docker_image:
        build:
          path: ./sample_api
     volumes:
          - "./simple_api:/usr/src/app"
     published_ports:
          - "5001:5000"
  
  - name: Run apache container
    docker_container:
    name: 'website'
    image: 'php:apache'
    published_ports:
          - "5000:80"
    volumes:
          - "./website:/var/www/html"
    env:
        USERNAME: "toto"
        PASSWORD: "python"
        
        
   
   
